spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrm?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        show_sql: true
#        format_sql: true
  flyway:
    table: flyway_schema_history
    locations: classpath:db/migrations