server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${DB_WRITER}/hrm?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        show_sql: true
#        format_sql: true
  flyway:
    locations: classpath:db/migrations