apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrm-app
  template:
    metadata:
      labels:
        app: hrm-app
        type: backend
    spec:
      containers:
        - name: spring-boot-container
          image: lukamakojevic/hrm:arm64
          ports:
            - containerPort: 8080
          env:
            - name: DB_WRITER
              value: mysql
            - name: DATASOURCE_USERNAME
              value: root
            - name: DATASOURCE_PASSWORD
              value: rootroot
