name: Run tests
on:
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '17'
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build and run tests
        run: mvn clean test
